// Global
export const RESET_STATE = 'CLEAR_STATE'

// Filters
export const TOGGLE_FILTER = 'TOGGLE_FILTER'

// Legend
export const UPDATE_LEGEND = 'UPDATE_LEGEND'
export const UPDATE_MINMAX = 'UPDATE_MINMAX'

// MapFeatures
export const SET_MAP = 'SET_MAP'
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES'
export const UPDATE_RENTS = 'UPDATE_RENTS'
export const UPDATE_METRIC = 'UPDATE_HEATMAP_DATA'
export const REMOVE_SURVEY = 'REMOVE_SURVEY'

// Property
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const FETCH_PLACE = 'FETCH_PLACE'
export const FETCH_PROPERTY = 'FETCH_PROPERTY'
export const UPDATE_NEIGHBORHOOD = 'UPDATE_NEIGHBORHOOD'

// Rent
export const UPDATE_RENT = 'UPDATE_RENT'
export const RESET_RENT = 'CLEAR_RENT'

// SelectedProperty
export const REMOVE_SELECTED_PROPERTY = 'REMOVE_SELECTED_PROPERTY'
export const SET_SELECTED_PROPERTY = 'SET_SELECTED_PROPERTY'
