export const SET_MAP = 'SET_MAP'
export const SET_SELECTED_PROPERTY = 'SET_SELECTED_PROPERTY'

export const UPDATE_COORDINATES = 'UPDATE_COORDINATES'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_POLYGON_IDS = 'UPDATE_POLYGON_IDS'
export const UPDATE_HEATMAP_DATA = 'UPDATE_HEATMAP_DATA'
export const UPDATE_RENT = 'UPDATE_RENT'
export const UPDATE_INCOME = 'UPDATE_INCOME'
export const UPDATE_LEGEND = 'UPDATE_LEGEND'

export const TOGGLE_FILTER = 'TOGGLE_FILTER'

export const REMOVE_SELECTED_PROPERTY = 'REMOVE_SELECTED_PROPERTY'

export const FETCH_PLACE = 'FETCH_PLACE'
export const FETCH_PROPERTY = 'FETCH_PROPERTY'
export const FETCH_INCOME = 'FETCH_INCOME'
export const FETCH_INCOMES = 'FETCH_INCOMES'
export const FETCH_RENT = 'FETCH_RENT'
export const FETCH_RENTS = 'FETCH_RENTS'

export const CLEAR_STATE = 'CLEAR_STATE'
export const CLEAR_RENT = 'CLEAR_RENT'
export const CLEAR_INCOME = 'CLEAR_INCOME'
